spring:
  application:
    name: product-service
  profiles:
    active: dev
  datasource:
    url: ${CATALOG_DB_URL:jdbc:postgresql://localhost:5432/product}
    username: ${CATALOG_DB_USERNAME:product}
    password: ${CATALOG_DB_PASSWORD:product}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        '[format_sql]': true
        jdbc:
          '[time_zone]': UTC
    show-sql: false
  flyway:
    enabled: true
    baseline-on-migrate: false
    locations: classpath:db/migration
  cache:
    type: caffeine
    cache-names: products,productById,productBySku,productBySlug
    caffeine:
      spec: maximumSize=500,expireAfterWrite=300s
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
server:
  port: 8081
logging:
  level:
    root: INFO
    '[org.springframework]': INFO
    '[com.loiane.catalog]': DEBUG
