version: "3.9"
services:
  postgres:
    image: postgres:16-alpine
    container_name: catalog-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${CATALOG_DB_NAME:-catalog}
      POSTGRES_USER: ${CATALOG_DB_USERNAME:-catalog}
      POSTGRES_PASSWORD: ${CATALOG_DB_PASSWORD:-catalog}
    ports:
      - "5432:5432"
    volumes:
      - pg_data_catalog:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
  adminer:
    image: adminer:4
    container_name: catalog-adminer
    restart: unless-stopped
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    ports:
      - "8085:8080"
    depends_on:
      - postgres
volumes:
  pg_data_catalog:
