version: "3.9"
services:
  postgres:
    image: postgres:16-alpine
    container_name: product-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${PRODUCT_DB_NAME:-product}
      POSTGRES_USER: ${PRODUCT_DB_USERNAME:-product}
      POSTGRES_PASSWORD: ${PRODUCT_DB_PASSWORD:-product}
    ports:
      - "5432:5432"
    volumes:
      - pg_data_product:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
  adminer:
    image: adminer:4
    container_name: catalog-adminer
    restart: unless-stopped
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    ports:
      - "8085:8080"
    depends_on:
      - postgres
volumes:
  pg_data_product:
